# SPDX-License-Identifier: MIT
"""Transactions du pool et helpers de dialecte (chantier multi-moteurs, lot A).

``db_tx()`` remplace les connexions privées qui comptaient sur le ``with`` de
sqlite3 (commit à la sortie, rollback sur exception) ; ``db_autocommit()``
celle de la mémoire AX. Le pool étant réentrant par thread, les deux doivent
se comporter correctement quand ils sont IMBRIQUÉS dans une transaction de
l'appelant : ni commit forcé du travail d'autrui, ni autocommit qui fuit.
"""
import pytest

from shared_infra.db import _connection as _legacy
from shared_infra.db import _dialect as D


@pytest.fixture
def dbfile(tmp_path, monkeypatch):
    monkeypatch.setattr(_legacy, "DB_PATH", str(tmp_path / "app.db"))
    _legacy.reset_pool()
    with _legacy.db_conn() as conn:
        # Table de travail au DDL de chaque moteur (la suite peut tourner sur
        # PostgreSQL ou MySQL, cf. tests/conftest.py).
        conn.execute({
            "postgres": "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v TEXT)",
            "mysql": "CREATE TABLE t (id BIGINT AUTO_INCREMENT PRIMARY KEY, v LONGTEXT)",
        }.get(D.dialect_of(conn), "CREATE TABLE t (id INTEGER PRIMARY KEY, v TEXT)"))
        conn.commit()
    yield tmp_path / "app.db"
    _legacy.reset_pool()


def _values():
    with _legacy.db_conn() as conn:
        return [r[0] for r in conn.execute("SELECT v FROM t ORDER BY id")]


# ── db_tx ────────────────────────────────────────────────────────────────────

def test_db_tx_valide_a_la_sortie(dbfile):
    with _legacy.db_tx() as c:
        c.execute("INSERT INTO t(v) VALUES ('a')")
    assert _values() == ["a"]


def test_db_tx_annule_sur_exception(dbfile):
    with pytest.raises(RuntimeError):
        with _legacy.db_tx() as c:
            c.execute("INSERT INTO t(v) VALUES ('a')")
            raise RuntimeError("boum")
    assert _values() == []


def test_db_tx_imbrique_ne_valide_pas_le_travail_de_l_appelant(dbfile):
    with _legacy.db_conn() as outer:
        outer.execute("INSERT INTO t(v) VALUES ('dehors')")
        with _legacy.db_tx() as inner:
            inner.execute("INSERT INTO t(v) VALUES ('dedans')")
        assert outer.in_transaction, "le bloc imbriqué a validé la transaction de l'appelant"
        outer.rollback()
    assert _values() == []


def test_db_tx_imbrique_n_annule_que_son_travail(dbfile):
    with _legacy.db_conn() as outer:
        outer.execute("INSERT INTO t(v) VALUES ('dehors')")
        with pytest.raises(RuntimeError):
            with _legacy.db_tx() as inner:
                inner.execute("INSERT INTO t(v) VALUES ('dedans')")
                raise RuntimeError("boum")
        outer.commit()
    assert _values() == ["dehors"]


def test_db_tx_rend_la_connexion_au_pool(dbfile):
    with _legacy.db_tx():
        pass
    assert getattr(_legacy._pool, "depth", 0) == 0


# ── db_autocommit ────────────────────────────────────────────────────────────

def test_db_autocommit_valide_chaque_instruction(dbfile):
    with _legacy.db_autocommit() as c:
        c.execute("INSERT INTO t(v) VALUES ('a')")
        assert not c.in_transaction
    assert _values() == ["a"]


def test_db_autocommit_rejoint_la_transaction_de_l_appelant(dbfile):
    with _legacy.db_conn() as outer:
        outer.execute("INSERT INTO t(v) VALUES ('dehors')")
        with _legacy.db_autocommit() as inner:
            inner.execute("INSERT INTO t(v) VALUES ('dedans')")
        assert outer.in_transaction, "l'autocommit a validé de force la transaction de l'appelant"
        outer.rollback()
    assert _values() == []


def test_db_autocommit_imbrique_ne_laisse_pas_l_appelant_en_autocommit(dbfile):
    with _legacy.db_conn() as outer:
        with _legacy.db_autocommit():
            pass
        assert outer.isolation_level == "", "l'appelant est resté en autocommit"
        outer.execute("INSERT INTO t(v) VALUES ('a')")
        assert outer.in_transaction


# ── Helpers de dialecte (branche SQLite = le SQL d'avant) ────────────────────

def test_begin_write_prend_le_verrou_d_ecriture(dbfile):
    with _legacy.db_autocommit() as c:
        D.begin_write(c)
        assert c.in_transaction
        c.execute("INSERT INTO t(v) VALUES ('a')")
        c.execute("COMMIT")
    assert _values() == ["a"]


def test_savepoint_n_annule_que_le_bloc(dbfile):
    with _legacy.db_conn() as c:
        c.execute("INSERT INTO t(v) VALUES ('garde')")
        with pytest.raises(Exception):
            with D.savepoint(c):
                c.execute("INSERT INTO t(v) VALUES ('perdu')")
                c.execute("INSERT INTO table_absente VALUES (1)")
        c.commit()
    assert _values() == ["garde"]


def test_introspection_et_ajout_de_colonne(dbfile):
    with _legacy.db_conn() as c:
        assert D.has_table(c, "t") and not D.has_table(c, "absente")
        assert D.table_columns(c, "t") == ["id", "v"]
        # MySQL n'accepte de défaut sur un TEXT qu'entre parenthèses ; SQLite
        # refuse justement les parenthèses dans ADD COLUMN.
        decl = ("TEXT NOT NULL DEFAULT ('')" if D.dialect_of(c) == "mysql"
                else "TEXT NOT NULL DEFAULT ''")
        assert D.add_column_if_missing(c, "t", "w", decl) is True
        assert D.add_column_if_missing(c, "t", "w", decl) is False
        assert D.has_column(c, "t", "w")


def test_is_missing_table(dbfile):
    with _legacy.db_conn() as c:
        with pytest.raises(Exception) as ei:
            c.execute("SELECT 1 FROM table_absente")
    assert D.is_missing_table(ei.value)
    assert not D.is_missing_table(ValueError("no such table"))


def test_insert_id(dbfile):
    with _legacy.db_conn() as c:
        cur = c.cursor()
        first = D.insert_id(cur, "INSERT INTO t(v) VALUES (?)", ("a",))
        second = D.insert_id(cur, "INSERT INTO t(v) VALUES (?)", ("b",))
        c.commit()
    assert second == first + 1


@pytest.mark.parametrize("dialect,attendu", [
    ("sqlite", "json_extract(tags_json, '$.user')"),
    ("postgres", "(CAST(tags_json AS JSONB) ->> 'user')"),
    ("mysql", "JSON_UNQUOTE(JSON_EXTRACT(tags_json, '$.user'))"),
])
def test_json_get(dialect, attendu):
    assert D.json_get("tags_json", "user", dialect=dialect) == attendu


def test_json_get_refuse_une_cle_non_identifiant():
    with pytest.raises(ValueError):
        D.json_get("tags_json", "a'; DROP TABLE t; --")


@pytest.mark.parametrize("dialect,attendu", [
    ("sqlite", "t.v LIKE ?"),
    ("postgres", "t.v ILIKE ?"),
    ("mysql", "LOWER(t.v) LIKE LOWER(?)"),
])
def test_ci_like(dialect, attendu):
    assert D.ci_like("t.v", dialect=dialect) == attendu


def test_fragments_sqlite_identiques_a_avant():
    """En SQLite, chaque helper rend le SQL qui s'écrivait avant lui."""
    q = dict(dialect="sqlite")
    assert D.cast_int("x", **q) == "CAST(x AS INTEGER)"
    assert D.round_("AVG(v)", 1, **q) == "ROUND(AVG(v), 1)"
    assert D.greatest("a", "b", **q) == "MAX(a, b)"
    assert D.no_limit(**q) == "-1"
    assert D.group_concat("name", **q) == "GROUP_CONCAT(name, ',')"
    assert D.nulls_first("parent_id", **q) == "parent_id ASC NULLS FIRST"


def test_fragments_s_executent(dbfile):
    with _legacy.db_conn() as c:
        c.execute("INSERT INTO t(v) VALUES ('{\"user\": \"alice\"}')")
        row = c.execute(
            f"SELECT {D.json_get('v', 'user')}, {D.cast_int('7.9')}, "
            f"{D.greatest('1', '3')}, {D.round_('2.345', 2)} FROM t").fetchone()
        c.rollback()
    assert tuple(row) == ("alice", 7, 3, 2.35)
