// SPDX-License-Identifier: MIT
// ============================================================================
//  frontend/js/admin/_fields.js — GÉNÉRÉ par tools/generate_admin_fields.py
//  Ne pas éditer à la main : relancer le script après avoir changé un gabarit
//  de la console (test : tests/frontend/test_admin_fields_index.py).
//  Index des réglages pour la recherche Ctrl+K : page, bloc:chemin, libellé.
// ============================================================================
window.ELPIS_ADMIN_FIELDS = Object.freeze([
    {"control": "", "hint": "Vide = le moteur d'inférence principal s'en charge.", "label": "Adresse", "page": "compression", "path": "endpoint_url", "store": "compression"},
    {"control": "", "hint": "N'active rien : chaque utilisateur reste libre de l'activer (désactivée par défaut).", "label": "Autorisée", "page": "compression", "path": "enabled", "store": "compression"},
    {"control": "", "hint": "Au-delà, le budget de contexte prend le relais. 0 = sans limite.", "label": "Compressions par conversation", "page": "compression", "path": "max_per_chat", "store": "compression"},
    {"control": "", "hint": "Un petit modèle rapide suffit.", "label": "Modèle", "page": "compression", "path": "endpoint_model", "store": "compression"},
    {"control": "Délai en secondes", "hint": "Un petit modèle rapide suffit.", "label": "Modèle", "page": "compression", "path": "endpoint_timeout_sec", "store": "compression"},
    {"control": "", "hint": "Part du contexte à partir de laquelle compacter, pour les comptes qui n'ont pas réglé le leur. 0 = fenêtre pleine.", "label": "Seuil par défaut (%)", "page": "compression", "path": "threshold_pct", "store": "compression"},
    {"control": "", "hint": "Même rôle, exprimé en tokens — prime sur le pourcentage ci-dessus. 0 = non utilisé.", "label": "Seuil par défaut (tokens)", "page": "compression", "path": "threshold_tokens", "store": "compression"},
    {"control": "", "hint": "Propose « Images » dans le menu + du chat. Chaque compte peut ensuite couper l'entrée dans ses Paramètres.", "label": "Activation", "page": "images", "path": "image.enabled", "store": "config"},
    {"control": "", "hint": "Vide = génération désactivée.", "label": "Adresse", "page": "images", "path": "image.url", "store": "config"},
    {"control": "", "hint": "Autorité de l'infrastructure interne, au format PEM. Vide : magasin du système.", "label": "CA", "page": "images", "path": "image.ca_pem", "store": "config"},
    {"control": "", "hint": "", "label": "Certificat", "page": "images", "path": "image.verify", "store": "config"},
    {"control": "", "hint": "Images gardées par compte ; les plus anciennes sont effacées.", "label": "Conserver", "page": "images", "path": "image.keep_per_user", "store": "config"},
    {"control": "", "hint": "Plus grand côté qu'un compte peut demander.", "label": "Côté max", "page": "images", "path": "image.max_side", "store": "config"},
    {"control": "", "hint": "Taille proposée à un compte qui n'a rien choisi.", "label": "Côté par défaut", "page": "images", "path": "image.default_side", "store": "config"},
    {"control": "", "hint": "Compté à partir du début du calcul (pas de l'attente en file).", "label": "Délai", "page": "images", "path": "image.timeout_sec", "store": "config"},
    {"control": "", "hint": "Le modèle du chat peut réécrire la description avant l'envoi au moteur.", "label": "Enrichir", "page": "images", "path": "image.enhance_enabled", "store": "config"},
    {"control": "Groupes autorisés", "hint": "Aucun groupe coché : tous les comptes. Les administrateurs ont toujours accès.", "label": "Groupes", "page": "images", "path": "image.groups", "store": "config"},
    {"control": "", "hint": "Séparées par des virgules.", "label": "Liste", "page": "images", "path": "image.sizes", "store": "config"},
    {"control": "", "hint": "Lu sur le serveur.", "label": "Modèle", "page": "images", "path": "image.model", "store": "config"},
    {"control": "", "hint": "", "label": "Moteur", "page": "images", "path": "image.provider", "store": "config"},
    {"control": "", "hint": "Appels de l'outil generate_image permis par tour du modèle.", "label": "Outil", "page": "images", "path": "image.tool_max_calls", "store": "config"},
    {"control": "", "hint": "", "label": "Par demande", "page": "images", "path": "image.max_n", "store": "config"},
    {"control": "", "hint": "Générations simultanées vers ce service, tous processus confondus.", "label": "Simultanées", "page": "images", "path": "image.max_concurrent", "store": "config"},
    {"control": "", "hint": "Fixes : les vrais modèles OpenAI n'acceptent que quelques tailles.", "label": "Tailles", "page": "images", "path": "image.size_policy", "store": "config"},
    {"control": "", "hint": "Comment le modèle chargé modifie une image.", "label": "Édition", "page": "images", "path": "image.edit_mode", "store": "config"},
    {"control": "Hôte", "hint": "Hôte, port, et délai maximal d'une requête.", "label": "Adresse", "page": "inference", "path": "llama.ip", "store": "config"},
    {"control": "Port", "hint": "Hôte, port, et délai maximal d'une requête.", "label": "Adresse", "page": "inference", "path": "llama.port", "store": "config"},
    {"control": "Délai en secondes", "hint": "Hôte, port, et délai maximal d'une requête.", "label": "Adresse", "page": "inference", "path": "llama.timeout_sec", "store": "config"},
    {"control": "Conversations par modèle", "hint": "Propre à llama.cpp : modèles chargés en parallèle, conversations par modèle.", "label": "Capacité", "page": "inference", "path": "llama.max_concurrency", "store": "config"},
    {"control": "Modèles simultanés", "hint": "Propre à llama.cpp : modèles chargés en parallèle, conversations par modèle.", "label": "Capacité", "page": "inference", "path": "llama.max_models", "store": "config"},
    {"control": "", "hint": "« Auto » choisit selon les capacités détectées du serveur.", "label": "Mode", "page": "inference", "path": "configured_mode", "store": "scheduling"},
    {"control": "", "hint": "Modèle par défaut : identifiant transmis à l'API (champ « model » de la requête).", "label": "Modèle", "page": "inference", "path": "llama.model", "store": "config"},
    {"control": "Tentatives", "hint": "Nombre de tentatives et délai initial (doublé à chaque essai).", "label": "Reprise sur échec", "page": "inference", "path": "llama.retries", "store": "config"},
    {"control": "Délai initial en secondes", "hint": "Nombre de tentatives et délai initial (doublé à chaque essai).", "label": "Reprise sur échec", "page": "inference", "path": "llama.retry_backoff_sec", "store": "config"},
    {"control": "", "hint": "Hors llama.cpp, l'app parle en OpenAI standard. Pris en compte au redémarrage.", "label": "Type", "page": "inference", "path": "llama.engine", "store": "config"},
    {"control": "", "hint": "Si renseignée, remplace hôte et port.", "label": "URL complète", "page": "inference", "path": "llama.url", "store": "config"},
    {"control": "", "hint": "Au-delà, les plus anciennes sont archivées.", "label": "Conversations récentes", "page": "instance", "path": "app.max_recent_chats", "store": "config"},
    {"control": "", "hint": "Cet écran ne suit pas le skin : il s'affiche avant la session.", "label": "Couleurs", "page": "instance", "path": "login_page.bg_color", "store": "config"},
    {"control": "", "hint": "Cet écran ne suit pas le skin : il s'affiche avant la session.", "label": "Couleurs", "page": "instance", "path": "login_page.btn_color", "store": "config"},
    {"control": "", "hint": "Cet écran ne suit pas le skin : il s'affiche avant la session.", "label": "Couleurs", "page": "instance", "path": "login_page.card_color", "store": "config"},
    {"control": "", "hint": "Cet écran ne suit pas le skin : il s'affiche avant la session.", "label": "Couleurs", "page": "instance", "path": "login_page.text_color", "store": "config"},
    {"control": "", "hint": "Texte court d'« À propos ». Facultatif.", "label": "Description", "page": "instance", "path": "app_info.description", "store": "config"},
    {"control": "Hauteur", "hint": "Largeur et hauteur maximales, en pixels.", "label": "Dimensions", "page": "instance", "path": "welcome.height", "store": "config"},
    {"control": "", "hint": "Fichiers joints par les utilisateurs.", "label": "Dossier des envois", "page": "instance", "path": "app.upload_dir", "store": "config"},
    {"control": "", "hint": "Un sous-dossier par utilisateur.", "label": "Dossier des sandboxes", "page": "instance", "path": "app.sandbox_dir", "store": "config"},
    {"control": "", "hint": "Panneau latéral et onglet du navigateur.", "label": "Icône", "page": "instance", "path": "app_info.icon_bg", "store": "config"},
    {"control": "", "hint": "Panneau latéral et onglet du navigateur.", "label": "Icône", "page": "instance", "path": "app_info.icon_color", "store": "config"},
    {"control": "", "hint": "Pictogramme central de la carte.", "label": "Icône", "page": "instance", "path": "login_page.icon_bg", "store": "config"},
    {"control": "", "hint": "Pictogramme central de la carte.", "label": "Icône", "page": "instance", "path": "login_page.icon_color", "store": "config"},
    {"control": "", "hint": "S'affiche à la place du visuel ci-dessus pour qui a choisi une mascotte dans ses paramètres. Aperçu à la taille réelle du bloc d'accueil.", "label": "Mot animé", "page": "instance", "path": "welcome.scene.mascot_scale", "store": "config"},
    {"control": "", "hint": "S'affiche à la place du visuel ci-dessus pour qui a choisi une mascotte dans ses paramètres. Aperçu à la taille réelle du bloc d'accueil.", "label": "Mot animé", "page": "instance", "path": "welcome.scene.motif", "store": "config"},
    {"control": "", "hint": "S'affiche à la place du visuel ci-dessus pour qui a choisi une mascotte dans ses paramètres. Aperçu à la taille réelle du bloc d'accueil.", "label": "Mot animé", "page": "instance", "path": "welcome.scene.word_scale", "store": "config"},
    {"control": "", "hint": "Libellé informatif d'« À propos ». Ne change aucun branchement.", "label": "Moteur affiché", "page": "instance", "path": "app_info.engine", "store": "config"},
    {"control": "", "hint": "Panneau latéral, onglet du navigateur.", "label": "Nom", "page": "instance", "path": "app_info.name", "store": "config"},
    {"control": "", "hint": "Taille en pixels du visuel affiché.", "label": "Pictogramme", "page": "instance", "path": "welcome.width", "store": "config"},
    {"control": "", "hint": "Équipe, environnement… Facultatif.", "label": "Sous-titre", "page": "instance", "path": "login_page.subtitle", "store": "config"},
    {"control": "", "hint": "En-tête de la carte de connexion.", "label": "Titre", "page": "instance", "path": "login_page.title", "store": "config"},
    {"control": "", "hint": "Les couleurs suivent le skin actif.", "label": "Type", "page": "instance", "path": "welcome.type", "store": "config"},
    {"control": "", "hint": "Format SemVer.", "label": "Version", "page": "instance", "path": "app_info.version", "store": "config"},
    {"control": "", "hint": "Crédit affiché dans « À propos ».", "label": "Équipe", "page": "instance", "path": "app_info.team_name", "store": "config"},
    {"control": "", "hint": "Coupée : découverte, consentement et jetons OAuth refusés ; les accès déjà accordés cessent de fonctionner. Suit aussi l'interrupteur des jetons d'outils.", "label": "Autorisation OAuth", "page": "mcp", "path": "mcp.oauth.enabled", "store": "config"},
    {"control": "", "hint": "0 = relire à chaque appel.", "label": "Cache de la liste d'outils", "page": "mcp", "path": "mcp.tools_cache_ttl_sec", "store": "config"},
    {"control": "", "hint": "Exécutable lancé en sous-processus.", "label": "Commande", "page": "mcp", "path": "mcp.server_cmd", "store": "config"},
    {"control": "", "hint": "Scanné au démarrage pour les serveurs MCP téléversés.", "label": "Dossier des serveurs ajoutés", "page": "mcp", "path": "mcp.servers_dir", "store": "config"},
    {"control": "", "hint": "Entre 300 et 86 400 secondes.", "label": "Durée d'un jeton d'accès", "page": "mcp", "path": "mcp.oauth.access_ttl_s", "store": "config"},
    {"control": "", "hint": "Borné par la durée maximale des jetons d'outils.", "label": "Durée d'une autorisation", "page": "mcp", "path": "mcp.oauth.refresh_days", "store": "config"},
    {"control": "", "hint": "0 = sans limite.", "label": "Durée maximale", "page": "mcp", "path": "mcp.tokens.max_days", "store": "config"},
    {"control": "", "hint": "Un client s'enregistre seul (RFC 7591). Redirections limitées à la boucle locale et à https. Coupé : seuls les clients déjà connus ou décrits par un document https sont acceptés.", "label": "Enregistrement dynamique", "page": "mcp", "path": "mcp.oauth.dcr_enabled", "store": "config"},
    {"control": "", "hint": "Séparées par des virgules, parmi fs, shell, git, desktop, browser, skill_run. Retirer une famille la retire aussitôt des jetons existants.", "label": "Familles autorisées", "page": "mcp", "path": "mcp.tokens.tools_families", "store": "config"},
    {"control": "", "hint": "Coupé : les jetons existants cessent de fonctionner et aucun ne peut être créé. Les jetons opencode ne sont pas concernés.", "label": "Jetons d'outils", "page": "mcp", "path": "mcp.tokens.tools_enabled", "store": "config"},
    {"control": "", "hint": "Jetons opencode et d'outils confondus.", "label": "Jetons par compte", "page": "mcp", "path": "mcp.tokens.max_per_user", "store": "config"},
    {"control": "", "hint": "Sans barre oblique finale.", "label": "Adresse", "page": "rag", "path": "rag.service_url", "store": "config"},
    {"control": "", "hint": "Au-delà, l'outil renvoie une erreur récupérable.", "label": "Délai maximal", "page": "rag", "path": "rag.service_timeout", "store": "config"},
    {"control": "", "hint": "Vide si le service est en accès ouvert.", "label": "Jeton", "page": "rag", "path": "rag.service_token", "store": "config"},
    {"control": "", "hint": "Word, PowerPoint et Excel dans l'éditeur. Conversion LibreOffice isolée (bubblewrap) sur le serveur. Les PDF restent visibles même désactivé.", "label": "Aperçu Office", "page": "rights", "path": "features.office_preview", "store": "config"},
    {"control": "", "hint": "Entrée du menu chat qui installe le CLI sur le poste de l'utilisateur.", "label": "OpenCode", "page": "rights", "path": "features.opencode", "store": "config"},
    {"control": "", "hint": "Affiche le choix du modèle et du connecteur dans le chat.", "label": "Sélecteur de modèle", "page": "rights", "path": "app.enable_model_selector", "store": "config"},
    {"control": "", "hint": "Seuil utilisé par « Recycler les inactifs ». 0 = jamais.", "label": "Arrêt d'inactivité", "page": "sandbox-limits", "path": "idle_kill_hours", "store": "exec"},
    {"control": "", "hint": "Au-delà, la commande est interrompue.", "label": "Durée d'une commande", "page": "sandbox-limits", "path": "limits.timeout_s", "store": "exec"},
    {"control": "", "hint": "Le mode dossier n'est plus proposé aux utilisateurs.", "label": "Forcer Docker pour tous", "page": "sandbox-limits", "path": "force_user_docker", "store": "exec"},
    {"control": "", "hint": "UID:GID des exécutions. 0:0 = root dans le container. Effet immédiat.", "label": "Identité", "page": "sandbox-limits", "path": "exec_user", "store": "exec"},
    {"control": "", "hint": "Plafond par container.", "label": "Mémoire", "page": "sandbox-limits", "path": "limits.memory_mb", "store": "exec"},
    {"control": "", "hint": "100 = un cœur complet.", "label": "Processeur", "page": "sandbox-limits", "path": "limits.cpu_quota_pct", "store": "exec"},
    {"control": "", "hint": "Garde-fou contre les fork bombs.", "label": "Processus", "page": "sandbox-limits", "path": "limits.pids_max", "store": "exec"},
    {"control": "", "hint": "gVisor (runsc), Kata… Vide = runtime Docker. Au redémarrage.", "label": "Runtime OCI", "page": "sandbox-limits", "path": "runtime", "store": "exec"},
    {"control": "", "hint": "Chaque case ajoute une contrainte.", "label": "Caractères obligatoires", "page": "sessions", "path": "security.password_policy.require_lowercase", "store": "config"},
    {"control": "", "hint": "Chaque case ajoute une contrainte.", "label": "Caractères obligatoires", "page": "sessions", "path": "security.password_policy.require_numbers", "store": "config"},
    {"control": "", "hint": "Chaque case ajoute une contrainte.", "label": "Caractères obligatoires", "page": "sessions", "path": "security.password_policy.require_special", "store": "config"},
    {"control": "", "hint": "Chaque case ajoute une contrainte.", "label": "Caractères obligatoires", "page": "sessions", "path": "security.password_policy.require_uppercase", "store": "config"},
    {"control": "", "hint": "Au-delà, reconnexion obligatoire. Effet immédiat après enregistrement.", "label": "Durée de connexion", "page": "sessions", "path": "security.session.max_age_sec", "store": "config"},
    {"control": "", "hint": "0 = jamais. Effet immédiat après enregistrement.", "label": "Déconnexion sur inactivité", "page": "sessions", "path": "security.session.idle_timeout_sec", "store": "config"},
    {"control": "", "hint": "0 = aucun minimum.", "label": "Longueur minimale", "page": "sessions", "path": "security.password_policy.min_length", "store": "config"},
    {"control": "", "hint": "Nécessite un redémarrage.", "label": "Nom du cookie", "page": "sessions", "path": "security.session.cookie_name", "store": "config"},
    {"control": "", "hint": "Portée du cookie. « strict » coupe les liens entrants ; « none » impose HTTPS. Nécessite un redémarrage.", "label": "Portée", "page": "sessions", "path": "security.session.same_site", "store": "config"},
    {"control": "", "hint": "Journal des appels d’outils. 0 = sans limite. Au redémarrage.", "label": "Appels d'outils", "page": "upkeep", "path": "maintenance.tool_metrics_retention_days", "store": "config"},
    {"control": "", "hint": "Événements de métriques. 0 = sans limite. Au redémarrage.", "label": "Compteurs", "page": "upkeep", "path": "maintenance.metrics_retention_days", "store": "config"},
    {"control": "", "hint": "Registre de consommation LLM (un tour par ligne). 0 = sans limite. Au redémarrage.", "label": "Consommation", "page": "upkeep", "path": "maintenance.usage_events_retention_days", "store": "config"},
    {"control": "", "hint": "Heure locale de la passe quotidienne : purges, compactage de la base, rapport. Au redémarrage.", "label": "Heure", "page": "upkeep", "path": "maintenance.hour", "store": "config"},
    {"control": "", "hint": "Historique indexé pour la recherche dans les conversations. 0 = sans limite. Au redémarrage.", "label": "Messages", "page": "upkeep", "path": "maintenance.session_messages_retention_days", "store": "config"},
    {"control": "", "hint": "Rapports quotidiens archivés. 0 = sans limite. Au redémarrage.", "label": "Rapports", "page": "upkeep", "path": "maintenance.daily_report_retention_days", "store": "config"},
    {"control": "", "hint": "Journal des exécutions de routines. 0 = sans limite. Au redémarrage.", "label": "Runs de routines", "page": "upkeep", "path": "maintenance.routine_runs_retention_days", "store": "config"},
    {"control": "", "hint": "Vide = annotation désactivée, seul l'arbre d'accessibilité est utilisé.", "label": "Adresse", "page": "vision", "path": "vision.endpoint_url", "store": "config"},
    {"control": "", "hint": "Comment lire les cadres renvoyés par le détecteur.", "label": "Format de réponse", "page": "vision", "path": "vision.format", "store": "config"},
    {"control": "", "hint": "JPEG allège fortement le transport ; l'OCR reste en PNG.", "label": "Format des captures", "page": "vision", "path": "desktop.screenshot_format", "store": "config"},
    {"control": "Qualité JPEG", "hint": "JPEG allège fortement le transport ; l'OCR reste en PNG.", "label": "Format des captures", "page": "vision", "path": "desktop.screenshot_quality", "store": "config"},
    {"control": "", "hint": "Vide = balayage exhaustif. Renseigné, la détection devient une recherche ciblée.", "label": "Indice de recherche", "page": "vision", "path": "vision.prompt", "store": "config"},
    {"control": "", "hint": "Indispensable avec le routeur llama.cpp pour viser le modèle vision.", "label": "Modèle", "page": "vision", "path": "vision.model", "store": "config"},
    {"control": "", "hint": "Les petites icônes de la barre système n'apparaissent qu'à la seconde passe.", "label": "Passes de détection", "page": "vision", "path": "vision.passes", "store": "config"},
    {"control": "", "hint": "Ouvre les réglages vocaux aux utilisateurs. Chaque utilisateur choisit ensuite, dans ses paramètres, s'il veut dicter et se faire lire les réponses.", "label": "Activation", "page": "voice", "path": "voice.enabled", "store": "config"},
    {"control": "", "hint": "Serveur whisper.cpp. Vide = dictée désactivée.", "label": "Adresse", "page": "voice", "path": "voice.stt.endpoint_url", "store": "config"},
    {"control": "", "hint": "Service Piper de deploy/voice/tts. Vide = lecture désactivée.", "label": "Adresse", "page": "voice", "path": "voice.tts.endpoint_url", "store": "config"},
    {"control": "", "hint": "", "label": "Certificat", "page": "voice", "path": "voice.stt.verify", "store": "config"},
    {"control": "", "hint": "", "label": "Certificat", "page": "voice", "path": "voice.tts.verify", "store": "config"},
    {"control": "", "hint": "", "label": "Format", "page": "voice", "path": "voice.stt.format", "store": "config"},
    {"control": "", "hint": "", "label": "Format", "page": "voice", "path": "voice.tts.format", "store": "config"},
    {"control": "", "hint": "", "label": "Jeton", "page": "voice", "path": "voice.stt.token", "store": "config"},
    {"control": "", "hint": "Service Elpis : contenu de token.env sur la machine de synthèse.", "label": "Jeton", "page": "voice", "path": "voice.tts.token", "store": "config"},
    {"control": "", "hint": "Code ISO à deux lettres. « auto » laisse le modèle deviner, au prix d'un peu de latence.", "label": "Langue", "page": "voice", "path": "voice.stt.language", "store": "config"},
    {"control": "", "hint": "Lu sur le serveur.", "label": "Modèle", "page": "voice", "path": "voice.stt.model", "store": "config"},
    {"control": "", "hint": "", "label": "Modèle", "page": "voice", "path": "voice.tts.model", "store": "config"},
    {"control": "", "hint": "Entre 0,5 et 2. Au-delà, la voix se dégrade.", "label": "Vitesse", "page": "voice", "path": "voice.tts.speed", "store": "config"},
    {"control": "", "hint": "Termes à reconnaître, séparés par des virgules. Noms propres, jargon métier, sigles. Sur des termes spécialisés, ce champ divise le taux d'erreur par trois.", "label": "Vocabulaire", "page": "voice", "path": "voice.stt.prompt", "store": "config"},
    {"control": "", "hint": "", "label": "Voix", "page": "voice", "path": "voice.tts.voice", "store": "config"}
]);
