# SPDX-License-Identifier: MIT
"""DDL SQLite des fixtures de tests → DDL du moteur serveur de la suite.

Beaucoup de tests créent à la main de petites tables en DDL SQLite (``id
INTEGER PRIMARY KEY``, ``TEXT PRIMARY KEY``, ``DEFAULT '{}'`` sur un texte…).
Quand la suite tourne sur PostgreSQL ou MySQL (``APP_DB_BACKEND``), ces
``CREATE TABLE`` sont traduits ICI, pour les tests seulement : le code de
l'application, lui, n'écrit plus aucun DDL hors du schéma de référence
(``tests/db/test_schema_reference_2026_09_26.py`` le vérifie).

Règles (volontairement simples, celles des fixtures existantes) :
* ``INTEGER PRIMARY KEY [AUTOINCREMENT]`` (alias du rowid en SQLite, donc
  numéroté tout seul) → identité (PG) / ``AUTO_INCREMENT`` ;
* ``INTEGER`` → ``BIGINT`` (MySQL exige le même type des deux côtés d'une
  clé étrangère, et le schéma de référence est en BIGINT) ; ``REAL`` →
  ``DOUBLE PRECISION`` / ``DOUBLE`` ;
* MySQL : colonne texte clé (inline ou dans ``PRIMARY KEY``/``UNIQUE``) →
  ``VARCHAR(191)``, autres textes → ``LONGTEXT`` avec défaut parenthésé.
"""
from __future__ import annotations

import re

_CREATE = re.compile(r"^\s*CREATE\s+(TEMP\w*\s+)?TABLE\b", re.I)
_ROWID = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?\b", re.I)


_INDEX_IFNE = re.compile(r"^(\s*CREATE\s+(?:UNIQUE\s+)?INDEX\s+)IF\s+NOT\s+EXISTS\s+", re.I)


def index_if_not_exists(sql: str) -> bool:
    """``CREATE INDEX IF NOT EXISTS`` : MySQL 8 ne connaît pas la clause."""
    return bool(_INDEX_IFNE.match(sql))


def translate(sql: str, dialect: str) -> str:
    if dialect == "mysql" and _INDEX_IFNE.match(sql):
        # Clause retirée ; le doublon (1061) est absorbé par l'appelant.
        return _INDEX_IFNE.sub(r"\1", sql, count=1)
    if not _CREATE.match(sql) or dialect not in ("postgres", "mysql"):
        return sql
    if dialect == "postgres":
        sql = _ROWID.sub("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
        sql = re.sub(r"\bINTEGER\b", "BIGINT", sql, flags=re.I)
        return re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql, flags=re.I)
    sql = _ROWID.sub("BIGINT AUTO_INCREMENT PRIMARY KEY", sql)
    sql = re.sub(r"\bINTEGER\b", "BIGINT", sql, flags=re.I)
    sql = re.sub(r"\bREAL\b", "DOUBLE", sql, flags=re.I)
    keyed = set()
    for grp in re.findall(r"(?:PRIMARY\s+KEY|UNIQUE)\s*\(([^)]*)\)", sql, flags=re.I):
        keyed.update(c.strip().strip('"`') for c in grp.split(","))
    for name in re.findall(r'(\"?\w+\"?)\s+TEXT\b(?=[^,]*\b(?:PRIMARY\s+KEY|UNIQUE)\b)', sql, flags=re.I):
        keyed.add(name.strip('"'))

    def col(m):
        name, rest = m.group(1), m.group(2)
        if name.strip('"') in keyed:
            return f"{name} VARCHAR(191){rest}"
        rest = re.sub(r"DEFAULT\s+('(?:[^']|'')*')", r"DEFAULT (\1)", rest, flags=re.I)
        return f"{name} LONGTEXT{rest}"

    return re.sub(r'(\"?\b\w+\b\"?)\s+TEXT\b([^,)]*)', col, sql, flags=re.I)



_INSERT = re.compile(r'^\s*INSERT\s+(?:OR\s+\w+\s+)?INTO\s+"?(\w+)"?\s*\(([^)]*)\)', re.I)


def explicit_id_table(sql: str):
    """Table d'un INSERT qui fixe lui-même la colonne ``id``, sinon None."""
    m = _INSERT.match(sql)
    if m and "id" in (c.strip().strip('"`').lower() for c in m.group(2).split(",")):
        return m.group(1)
    return None


def resync_identity(conn, table: str) -> None:
    """PostgreSQL : une identité n'avance pas quand la fixture fournit l'id
    (SQLite repart de max(rowid)+1, MySQL aussi) → recalée juste après, sans
    quoi l'insertion suivante sans id heurterait la clé primaire."""
    _, rows, _ = conn._exec("SELECT pg_get_serial_sequence(?, 'id')", (f'"{table}"',), False)
    if rows and rows[0][0]:
        conn._exec(f'SELECT setval(?, (SELECT COALESCE(MAX(id), 0) FROM "{table}") + 1, false)',
                   (rows[0][0],), False)


__all__ = ["explicit_id_table", "index_if_not_exists", "resync_identity", "translate"]
